/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Address = string;
export interface Customer {
  'id' : CustomerId,
  'name' : Name,
  'email' : Email,
  'address' : Address,
  'phone' : PhoneNumber,
}
export type CustomerId = bigint;
export type Description = string;
export type Email = string;
export interface Invoice {
  'id' : InvoiceId,
  'isPaid' : boolean,
  'amountPaid' : bigint,
  'customerId' : CustomerId,
  'amountDue' : bigint,
  'items' : Array<InvoiceLineItem>,
}
export type InvoiceId = bigint;
export interface InvoiceLineItem {
  'description' : Description,
  'quantity' : Quantity,
  'unitPrice' : Price,
}
export type Name = string;
export type PhoneNumber = string;
export type Price = bigint;
export type Quantity = bigint;
export interface _SERVICE {
  'addCustomer' : ActorMethod<
    [string, PhoneNumber, Address, Email],
    CustomerId
  >,
  'createInvoice' : ActorMethod<
    [CustomerId, Array<InvoiceLineItem>],
    InvoiceId
  >,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [Invoice]>,
  'recordPayment' : ActorMethod<[InvoiceId, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];