/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PhoneNumber = IDL.Text;
export const Address = IDL.Text;
export const Email = IDL.Text;
export const CustomerId = IDL.Nat;
export const Description = IDL.Text;
export const Quantity = IDL.Nat;
export const Price = IDL.Nat;
export const InvoiceLineItem = IDL.Record({
  'description' : Description,
  'quantity' : Quantity,
  'unitPrice' : Price,
});
export const InvoiceId = IDL.Nat;
export const Name = IDL.Text;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : Name,
  'email' : Email,
  'address' : Address,
  'phone' : PhoneNumber,
});
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'isPaid' : IDL.Bool,
  'amountPaid' : IDL.Nat,
  'customerId' : CustomerId,
  'amountDue' : IDL.Nat,
  'items' : IDL.Vec(InvoiceLineItem),
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func(
      [IDL.Text, PhoneNumber, Address, Email],
      [CustomerId],
      [],
    ),
  'createInvoice' : IDL.Func(
      [CustomerId, IDL.Vec(InvoiceLineItem)],
      [InvoiceId],
      [],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'recordPayment' : IDL.Func([InvoiceId, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PhoneNumber = IDL.Text;
  const Address = IDL.Text;
  const Email = IDL.Text;
  const CustomerId = IDL.Nat;
  const Description = IDL.Text;
  const Quantity = IDL.Nat;
  const Price = IDL.Nat;
  const InvoiceLineItem = IDL.Record({
    'description' : Description,
    'quantity' : Quantity,
    'unitPrice' : Price,
  });
  const InvoiceId = IDL.Nat;
  const Name = IDL.Text;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : Name,
    'email' : Email,
    'address' : Address,
    'phone' : PhoneNumber,
  });
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'isPaid' : IDL.Bool,
    'amountPaid' : IDL.Nat,
    'customerId' : CustomerId,
    'amountDue' : IDL.Nat,
    'items' : IDL.Vec(InvoiceLineItem),
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func(
        [IDL.Text, PhoneNumber, Address, Email],
        [CustomerId],
        [],
      ),
    'createInvoice' : IDL.Func(
        [CustomerId, IDL.Vec(InvoiceLineItem)],
        [InvoiceId],
        [],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'recordPayment' : IDL.Func([InvoiceId, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };